import 'package:equatable/equatable.dart';
import 'package:lume/domain/entities/recommendation.dart';

/// States for the [RecommendationBloc].
abstract class RecommendationState extends Equatable {
  const RecommendationState();

  @override
  List<Object?> get props => [];
}

/// Initial state — no recommendations requested yet.
class RecommendationInitial extends RecommendationState {}

/// Recommendations are being generated by the AI.
class RecommendationLoading extends RecommendationState {}

/// Recommendations have been successfully generated.
class RecommendationLoaded extends RecommendationState {
  final RecommendationResult result;

  const RecommendationLoaded(this.result);

  @override
  List<Object?> get props => [result];
}

/// An error occurred while generating recommendations.
class RecommendationError extends RecommendationState {
  final String message;

  const RecommendationError(this.message);

  @override
  List<Object?> get props => [message];
}
